package team.left.shoppingmall.member.dao;

import java.util.HashMap;
import java.util.Map;

import team.left.shoppingmall.global.JdbcSupport;

public class MemberDao {
    
    /**
     * 회원을 저장한다.
     * 
     * @return auto-generated key
     */
    public int insertMember(MemberCreationDto dto) {
        System.out.println("dto=" + dto);
        
        String sql = "INSERT INTO member "
                + "(member_id, email, password, member_name, profile_img, birth_date, tel, address, gender, point, role, company, answer, is_deleted) "
                + "VALUES "
                + "(member_pk_seq.NEXTVAL, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        
        Map<Integer, Object> params = new HashMap<>();
        
        params.put(1, dto.getEmail());
        params.put(2, dto.getPassword());
        params.put(3, dto.getMemberName());
        params.put(4, dto.getProfileImg());
        params.put(5, dto.getBirthDate());
        params.put(6, dto.getTel());
        params.put(7, dto.getAddress());
        params.put(8, dto.getGender());
        params.put(9, dto.getPoint());
        params.put(10, dto.getRole());
        params.put(11, dto.getCompany());
        params.put(12, dto.getAnswer());
        params.put(13, dto.isDeleted());
        
        int autogeneratedKey = JdbcSupport.insertOne(sql, params, "member_id");
        System.out.println("autogeneratedKey=" + autogeneratedKey);
        return autogeneratedKey;
    }
}
